<?php
/**
 * TPPublisherExportCreateApiTest
 * PHP version 5
 *
 * @category Class
 * @package  
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace api;

use \\Configuration;
use \\ApiClient;
use \\ApiException;
use \\ObjectSerializer;

/**
 * TPPublisherExportCreateApiTest Class Doc Comment
 *
 * @category Class
 * @package  
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TPPublisherExportCreateApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for createAccessReportExportRequest
     *
     * Create access report
     *
     */
    public function test_createAccessReportExportRequest() {

    }
    
    /**
     * Test case for createDailyActivityReportExportRequest
     *
     * Create daily activity report
     *
     */
    public function test_createDailyActivityReportExportRequest() {

    }
    
    /**
     * Test case for createMonthlyActivityReportExportRequest
     *
     * Create monthly activity report
     *
     */
    public function test_createMonthlyActivityReportExportRequest() {

    }
    
    /**
     * Test case for createSubscriptionDetailedExportRequest
     *
     * Create subscription detail report
     *
     */
    public function test_createSubscriptionDetailedExportRequest() {

    }
    
    /**
     * Test case for createSubscriptionDetailedReportRequest
     *
     * Create subscription details report
     *
     */
    public function test_createSubscriptionDetailedReportRequest() {

    }
    
    /**
     * Test case for createSubscriptionSummaryExportRequest
     *
     * Create new downloadable subscription summary report and run it
     *
     */
    public function test_createSubscriptionSummaryExportRequest() {

    }
    
    /**
     * Test case for createSubscriptionSummaryReportRequest
     *
     * Create subscription summary report
     *
     */
    public function test_createSubscriptionSummaryReportRequest() {

    }
    
    /**
     * Test case for createTransactionsExportRequest
     *
     * Create new downloadable transactions report and run it
     *
     */
    public function test_createTransactionsExportRequest() {

    }
    
    /**
     * Test case for createUserExportRequest
     *
     * Create user search report
     *
     */
    public function test_createUserExportRequest() {

    }
    
}
