<?php
/**
 * TPPublisherInquiryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace api;

use \\Configuration;
use \\ApiClient;
use \\ApiException;
use \\ObjectSerializer;

/**
 * TPPublisherInquiryApiTest Class Doc Comment
 *
 * @category Class
 * @package  
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TPPublisherInquiryApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for addCommentRequest
     *
     * Adds comment
     *
     */
    public function test_addCommentRequest() {

    }
    
    /**
     * Test case for commentsRequest
     *
     * Lists inquiry comments
     *
     */
    public function test_commentsRequest() {

    }
    
    /**
     * Test case for detailsRequest
     *
     * Get inqiury
     *
     */
    public function test_detailsRequest() {

    }
    
    /**
     * Test case for getInquiryActionsRequest
     *
     * Available actions for an inquiry
     *
     */
    public function test_getInquiryActionsRequest() {

    }
    
    /**
     * Test case for lastCommentRequest
     *
     * Get last inquiry comment for user
     *
     */
    public function test_lastCommentRequest() {

    }
    
    /**
     * Test case for listRequest
     *
     * Lists inquiries
     *
     */
    public function test_listRequest() {

    }
    
    /**
     * Test case for unresolvedCountRequest
     *
     * Get unresolved inquiries count
     *
     */
    public function test_unresolvedCountRequest() {

    }
    
}
