<?php
/**
 * TPPublisherResourceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace api;

use \\Configuration;
use \\ApiClient;
use \\ApiException;
use \\ObjectSerializer;

/**
 * TPPublisherResourceApiTest Class Doc Comment
 *
 * @category Class
 * @package  
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TPPublisherResourceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for attachResourceToFixedBundleRequest
     *
     * Attach resource(s) to a fixed bundle
     *
     */
    public function test_attachResourceToFixedBundleRequest() {

    }
    
    /**
     * Test case for countRequest
     *
     * Lists total number of resources
     *
     */
    public function test_countRequest() {

    }
    
    /**
     * Test case for createResourceRequest
     *
     * Creates a resource
     *
     */
    public function test_createResourceRequest() {

    }
    
    /**
     * Test case for deleteResourceRequest
     *
     * Delete a resource
     *
     */
    public function test_deleteResourceRequest() {

    }
    
    /**
     * Test case for detachResourceFromFixedBundleRequest
     *
     * Detach a resource from a fixed bundle
     *
     */
    public function test_detachResourceFromFixedBundleRequest() {

    }
    
    /**
     * Test case for disableResourceRequest
     *
     * Disable one or more resources
     *
     */
    public function test_disableResourceRequest() {

    }
    
    /**
     * Test case for enableResourceRequest
     *
     * Enable one or more resources
     *
     */
    public function test_enableResourceRequest() {

    }
    
    /**
     * Test case for getResourceRequest
     *
     * Get a resource
     *
     */
    public function test_getResourceRequest() {

    }
    
    /**
     * Test case for listBundlesRequest
     *
     * Lists bundles that a resource belongs to
     *
     */
    public function test_listBundlesRequest() {

    }
    
    /**
     * Test case for listResourcesRequest
     *
     * Lists resources
     *
     */
    public function test_listResourcesRequest() {

    }
    
    /**
     * Test case for updateResourceRequest
     *
     * Update a resource
     *
     */
    public function test_updateResourceRequest() {

    }
    
}
