<?php
/**
 * TPPublisherUserAccessApiTest
 * PHP version 5
 *
 * @category Class
 * @package  
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace api;

use \\Configuration;
use \\ApiClient;
use \\ApiException;
use \\ObjectSerializer;

/**
 * TPPublisherUserAccessApiTest Class Doc Comment
 *
 * @category Class
 * @package  
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TPPublisherUserAccessApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for checkAccessRequest
     *
     * Check if user has access to a specific resource
     *
     */
    public function test_checkAccessRequest() {

    }
    
    /**
     * Test case for grantAccessRequest
     *
     * Grants access to a user
     *
     */
    public function test_grantAccessRequest() {

    }
    
    /**
     * Test case for grantAccessToUsersRequest
     *
     * Grant access to users
     *
     */
    public function test_grantAccessToUsersRequest() {

    }
    
    /**
     * Test case for listAccessRequest
     *
     * Lists a user's access
     *
     */
    public function test_listAccessRequest() {

    }
    
    /**
     * Test case for revokeAccessRequest
     *
     * Revokes a user's access
     *
     */
    public function test_revokeAccessRequest() {

    }
    
    /**
     * Test case for updateRequest
     *
     * Update user access
     *
     */
    public function test_updateRequest() {

    }
    
}
